name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rspec:
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
        activerecord:
          - '6.1'
          - '7.0'
          - '7.1'
    runs-on: ubuntu-latest

    name: RSpec (Rails ${{ matrix.activerecord }}) (Ruby ${{ matrix.ruby }})

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle install --with development && bundle exec appraisal activerecord-${{ matrix.activerecord }} rspec
